import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import { Badge } from '@/components/ui/badge'
import { Textarea } from '@/components/ui/textarea'
import { PageContainer } from '@/components/layout/PageContainer'
import { AppShell } from '@/components/layout/AppShell'
import { useToast } from '@/hooks/useToast'
import { getStoryService } from '@/services'
import { FileText, Clock, Users, Save, Sparkles, History, Stethoscope, RotateCcw } from 'lucide-react'
import type { Story } from '@/types'

const unwrap = <T,>(res: any): T => (res?.data?.data ?? res?.data ?? res) as T

export function StoryWorkspacePage() {
  const { id } = useParams(); const navigate = useNavigate(); const { success, error } = useToast()
  const [story, setStory] = useState<Story | null>(null); const [versions, setVersions] = useState<Story[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [rewrite, setRewrite] = useState(''); const [doctor, setDoctor] = useState<{score:number;issues:string[];suggestions:string[]}|null>(null)
  const load = useCallback(async () => { if (!id) return; setLoading(true); try { const s=await getStoryService(); const result=unwrap<Story>(await s.getStory(id)); setStory(result); } catch(e:any){ error('Unable to load story', e?.message || 'Story not found') } finally { setLoading(false) } }, [id])
  useEffect(()=>{ load() },[load])
  const save = async () => { if(!id||!story)return; setSaving(true); try { const s=await getStoryService(); setStory(unwrap<Story>(await s.updateStory(id,{title:story.title,logline:story.logline,synopsis:story.synopsis,fullStory:story.fullStory}))); success('Saved','Story changes saved successfully.') } catch(e:any){error('Save failed',e?.message||'Unable to save')} finally{setSaving(false)} }
  const loadVersions = async () => { if(!id)return; try { setVersions(unwrap<Story[]>(await (await getStoryService()).getVersions(id)) || []) } catch(e:any){error('Versions unavailable',e?.message||'Unable to load versions')} }
  const runRewrite = async () => { if(!id||!rewrite.trim())return; try { await (await getStoryService()).rewrite(id,rewrite,story?.fullStory); success('Rewrite requested','The AI rewrite has been submitted. Refreshing story...'); setRewrite(''); setTimeout(load,1000) } catch(e:any){error('Rewrite failed',e?.message||'Unable to rewrite story')} }
  const runDoctor = async () => { if(!id)return; try { setDoctor(unwrap(await (await getStoryService()).doctorAnalyze(id))); success('Story Doctor complete','Quality analysis is ready.') } catch(e:any){error('Analysis failed',e?.message||'Unable to analyze story')} }
  const restore = async (versionId:string) => { if(!id)return; try { setStory(unwrap<Story>(await (await getStoryService()).restoreVersion(id,versionId))); success('Version restored','The selected version is now current.') } catch(e:any){error('Restore failed',e?.message||'Unable to restore version')} }
  if(loading)return <AppShell><PageContainer maxWidth="7xl"><div className="py-20 text-center text-muted-foreground">Loading Story Workspace…</div></PageContainer></AppShell>
  if(!story)return <AppShell><PageContainer maxWidth="7xl"><Card className="p-10 text-center"><h2 className="text-xl font-semibold">No story found</h2><Button className="mt-4" onClick={()=>navigate('/studio/story')}>Create a Story</Button></Card></PageContainer></AppShell>
  return <AppShell><PageContainer maxWidth="7xl">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6"><div><h1 className="text-3xl font-display font-bold">{story.title}</h1><div className="flex flex-wrap items-center gap-3 mt-2"><Badge variant="studio">{story.culturalMode} • {story.genre}</Badge><span className="text-sm text-muted-foreground flex items-center gap-1"><Clock className="h-3 w-3"/>{story.estimatedDuration} min • {story.wordCount} words</span></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={loadVersions}><History className="mr-2 h-4 w-4"/> Versions</Button><Button variant="outline" onClick={runDoctor}><Stethoscope className="mr-2 h-4 w-4"/> Story Doctor</Button><Button variant="studio" onClick={save} isLoading={saving}><Save className="mr-2 h-4 w-4"/> Save</Button></div></div>
    <Tabs defaultValue="full"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="full">Full Story</TabsTrigger><TabsTrigger value="rewrite">AI Rewrite</TabsTrigger><TabsTrigger value="versions">Versions</TabsTrigger><TabsTrigger value="doctor">Doctor</TabsTrigger></TabsList>
      <TabsContent value="overview" className="mt-6 space-y-6"><Card><CardHeader><CardTitle>Story Details</CardTitle></CardHeader><CardContent className="space-y-4"><Textarea label="Title" value={story.title} onChange={e=>setStory({...story,title:e.target.value})}/><Textarea label="Logline" value={story.logline} onChange={e=>setStory({...story,logline:e.target.value})} rows={2}/><Textarea label="Synopsis" value={story.synopsis} onChange={e=>setStory({...story,synopsis:e.target.value})} rows={5}/><div className="grid md:grid-cols-3 gap-4 text-sm"><div className="p-4 rounded-xl bg-muted/50"><Users className="h-4 w-4 mb-2"/>Characters are ready for the next studio phase.</div><div className="p-4 rounded-xl bg-muted/50"><FileText className="h-4 w-4 mb-2"/>Versioned story editing enabled.</div><div className="p-4 rounded-xl bg-muted/50"><Sparkles className="h-4 w-4 mb-2"/>AI rewrite and Story Doctor connected.</div></div></CardContent></Card></TabsContent>
      <TabsContent value="full" className="mt-6"><Card><CardHeader><CardTitle>Full Story</CardTitle></CardHeader><CardContent><Textarea value={story.fullStory} onChange={e=>setStory({...story,fullStory:e.target.value})} rows={28} className="font-serif leading-7"/><p className="text-xs text-muted-foreground mt-2">Edits are versioned when saved.</p></CardContent></Card></TabsContent>
      <TabsContent value="rewrite" className="mt-6"><Card><CardHeader><CardTitle>AI Rewrite Studio</CardTitle></CardHeader><CardContent className="space-y-4"><Textarea label="Rewrite instruction" value={rewrite} onChange={e=>setRewrite(e.target.value)} rows={5} placeholder="Make the opening more emotional, improve dialogue, shorten the middle, etc."/><Button variant="studio" onClick={runRewrite} disabled={!rewrite.trim()}><Sparkles className="mr-2 h-4 w-4"/> Rewrite with AI</Button></CardContent></Card></TabsContent>
      <TabsContent value="versions" className="mt-6"><Card><CardHeader><CardTitle>Version History</CardTitle></CardHeader><CardContent>{versions.length===0?<Button variant="outline" onClick={loadVersions}>Load versions</Button>:<div className="space-y-3">{versions.map((v:any)=><div key={v.id} className="flex items-center justify-between p-4 rounded-xl bg-muted/40"><div><div className="font-medium">Version {v.version}</div><div className="text-xs text-muted-foreground">{v.changeNotes||'Saved story version'} • {v.createdAt?new Date(v.createdAt).toLocaleString():''}</div></div><Button variant="outline" size="sm" onClick={()=>restore(v.id)}><RotateCcw className="mr-2 h-4 w-4"/> Restore</Button></div>)}</div>}</CardContent></Card></TabsContent>
      <TabsContent value="doctor" className="mt-6"><Card><CardHeader><CardTitle>Story Doctor</CardTitle></CardHeader><CardContent>{!doctor?<Button variant="studio" onClick={runDoctor}><Stethoscope className="mr-2 h-4 w-4"/> Analyze Story</Button>:<div className="space-y-5"><div className="text-4xl font-bold">{doctor.score}/100</div><div><h4 className="font-semibold">Issues</h4>{doctor.issues.length?<ul className="list-disc pl-5 text-sm text-muted-foreground">{doctor.issues.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="text-sm text-muted-foreground">No major issues detected.</p>}</div><div><h4 className="font-semibold">Suggestions</h4><ul className="list-disc pl-5 text-sm text-muted-foreground">{doctor.suggestions.map((x,i)=><li key={i}>{x}</li>)}</ul></div></div>}</CardContent></Card></TabsContent>
    </Tabs>
  </PageContainer></AppShell>
}
